export const homeObjectOne = {
  id: 'about',
  lightBg: false,
  lightText: true,
  lightTextDescription: true,
  topLine: 'Premium Bank',
  headline: 'Unlimited Transactions with zero fees',
  description: 'Get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees.',
  buttonLabel: 'Get started',
  imgStart: false,
  img: require('../../images/svg-1.svg').default,
  alt: 'Car',
  dark: true,
  primary: true,
  darkText: false,
};

export const homeObjectTwo = {
  id: 'discover',
  lightBg: true,
  lightText: false,
  lightTextDescription: false,
  topLine: 'Unlimited Access',
  headline: 'Login to your account at any time',
  description: 'We have you covered no matter where you are located. All you need is an internet connection and a phone or computer.',
  buttonLabel: 'Learn More',
  imgStart: true,
  img: require('../../images/svg-2.svg').default,
  alt: 'Piggybank',
  dark: false,
  primary: false,
  darkText: true,
};

export const homeObjectThree = {
  id: 'signup',
  lightBg: true,
  lightText: false,
  lightTextDescription: false,
  topLine: 'Join our Team',
  headline: 'Creating an account is extremely easy',
  description: "Get everything set up and ready in under 10 minutes. All you need to do is add your information and you're ready to go.",
  buttonLabel: 'Start Now',
  imgStart: false,
  img: require('../../images/svg-4.svg').default,
  alt: 'Chart',
  dark: false,
  primary: false,
  darkText: true,
};